project:
  type: website

website:
  title: "Mini-Project-Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cancellations.qmd
      - delay.qmd
      - map.qmd
      - time-trends.qmd
      - Dashboard.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



